thrift/0.9.0/cxx11-compat.patch
thrift/0.9.0/remove-tr1-dependency.patch
thrift/0.9.0/tsocket.patch
thrift/0.9.0/use-boost-cpp-client-server.patch

Moving patches from my own gist repository (https://gist.github.com/rafaelverger/2602feff4050df0693c5/) to here.

thrift090: Moving patches from gist archive

---

freeimage/gcc5.diff

a patch for https://github.com/Homebrew/homebrew/pull/44612

freeimage: gcc5.0 patch

---

moc/moc-2.5.0.diff

Per discussion in https://github.com/Homebrew/homebrew/pull/49359.
CC @DomT4.

moc 2.5.0 patch

---

bash/bash-4.3.42.diff

bash: Add Patch

---

boost/boost1_60_0_python_class_metadata.diff

Patch for https://github.com/Homebrew/homebrew-core/pull/516

boost: Fix auto-pointer registration in 1.60

---

tinyscheme/patch-makefile.diff

cc @ilovezfs @DomT4 
Reference: Homebrew/homebrew-core#999

tinyscheme: migrate patch

---

lua/lua-5.2.3-sig_catch.patch

This is one of the patches for Lua. Submitting here as requested in [#1367](https://github.com/Homebrew/homebrew-core/pull/1367)

lua 5.2.3 sig_catch patch

---

unzip/unzip-6.0-20ubuntu1-series.patch

See the Ubuntu unzip package changelog for included fixes:
http://changelogs.ubuntu.com/changelogs/pool/main/u/unzip/unzip_6.0-20ubuntu1/changelog
Required for unzip package in homebrew-dupes, see Homebrew/homebrew-dupes#613.

Add patch series from ubuntu unzip-6.0-20ubuntu1

---

lsof/lsof-489-darwin-compile-fix.patch

See Homebrew/homebrew-dupes#616.

lsof 4.89 compile fix

---

hunspell/prepend_user_home_to_useroodirs.diff

fixes issue (hunspell/hunspell/issues/32)
hunspell does not prepend $HOME to all USEROODIRs

fixes issue (hunspell/hunspell/issues/32)

---

sdl_image/IMG_ImageIO.m.patch

As suggested in Homebrew/homebrew-core#1864. Adopted from [MacPorts](https://trac.macports.org/ticket/37453).

sdl_image: fix graphical glitching

---

qt5/QTBUG-54110.patch

Bug originally reported at <https://bugreports.qt.io/browse/QTBUG-54110>.

qt5:  Add patch to fix QTBUG-54110

---

qt5/QTBUG-54486.patch

I merged the diffs from https://codereview.qt-project.org/#/c/164100/ and https://codereview.qt-project.org/#/c/164101/ into a single patch file. This should fix the issues with Homebrew/homebrew-core#2087

qt5: Add patch for QTBUG-54486

---

qt5/QTBUG-54190.patch

https://codereview.qt-project.org/#/c/163076
This is for Homebrew/homebrew-core#2087

qt5: Add patch for QTBUG-54190

---

tinyscheme/patch-makefile.diff

Reference: https://github.com/Homebrew/formula-patches/pull/19#issuecomment-233226441

tinyscheme: Amend makefile patch to include init.scm.

---

opencsg/patch-build.diff

See https://github.com/Homebrew/homebrew-core/pull/2409
The patch has been submitted upstream.

OpenCSG build system patch

---

fontconfig/patch-2.12.1-fccache.diff

Patch from upstream maintainer Akira TAGOH:
https://bugs.freedesktop.org/show_bug.cgi?id=97546#c7

fontconfig: patch for caching bug in 2.12.1

---

plplot/cmake-3.6.patch

Patches taken from master:
https://sourceforge.net/p/plplot/plplot/ci/11c496bebb2d23f86812c753e60e7a5b8bbfb0a0/
https://sourceforge.net/p/plplot/plplot/ci/cac0198537a260fcb413f7d97301979c2dfaa31c/
Soon to be included in a `homebrew-core` PR...

plplot: fix build with CMake 3.6

---

opencsg/disable-examples.diff

Depends on Homebrew/homebrew-core#5088

Removed patch no longer needed since OpenCSG-1.4.1

---

glib/gio.patch

Necessary for Homebrew/homebrew-core#5109

glib 2.50.0 gio.patch update

---

gtkmm3/gtk_clipboard_get_selection.patch

Necessary for my soon to be added gtkmm3 PR

gtkmm3: work around gtk+3 bug

---

gnome-builder/pipe2.patch

For the upcoming 3.22.0 update I intend to submit later today...

gnome builder: missing pipe2 patch

---

pypy/patch-clock_gettime.diff

https://bitbucket.org/pypy/pypy/issues/2407/#comment-31210382
https://bitbucket.org/pypy/pypy/commits/91b44e61f628

pypy: patch for Xcode 8 clock_gettime issue

---

fastd/patch-xcode8-clock_gettime.diff

https://projects.universe-factory.net/issues/239
https://projects.universe-factory.net/projects/fastd/repository/revisions/2fa2187

fastd: patch for Xcode 8 clock_gettime

---

io/io.patch

https://github.com/stevedekorte/io/issues/333#issuecomment-249376400
Before updating homebrew-core, this patch must be merged.
Or if patch format is wrong, please tell me the right way?

io: fix build on Sierra

---

p11-kit/p11-kit-proxy-so-link.patch

https://bugs.freedesktop.org/show_bug.cgi?id=98022
https://cgit.freedesktop.org/p11-glue/p11-kit/commit/?id=6923e8fb56692b20d24398d4746d2399490acdc1

p11-kit: p11-kit-proxy.so symlink fix

---

valgrind/bzero.diff

valgrind: patch for __bzero undefined error

---

zsh/nvcs-formats-fix.patch

Patch for https://github.com/Homebrew/homebrew-core/pull/5607

Add patch for nvcsformats zsh

---

gdb/0001-darwin-nat.c-handle-Darwin-16-aka-Sierra.patch

Needed for https://github.com/Homebrew/homebrew-core/pull/6805.

Added patch for Sierra.

---

qt@5.5/qtconnectivity-bluetooth-fix-2.patch

For https://github.com/Homebrew/homebrew-core/pull/7555.

qt@5.5: additional MaxOSX10.12 SDK bluetooth fixes

---

python/brewed-tk-patch.diff

Existing patch pulled out of python.rb (previously embedded).

python: patch for brewed tk

---

openmotif/patch-configure.ac.diff
openmotif/patch-demos-xrmLib.c.diff
openmotif/patch-lib-VendorS.c.diff
openmotif/patch-lib-XmP.h.diff

See homebrew/homebrew-x11#289.
This includes the whitespace fixes I first submitted there.

openmotif: migrate patches

---

magnetix/avfoundation.patch

Submitted to the developer by email.
cc @ilovezfs

magnetix: add AVFoundation patch

---

libav/Check-for--no_weak_imports-in-ldflags-on-macOS.patch

Goes with https://github.com/Homebrew/homebrew-core/pull/10655

libav: patch for clock_gettime error on 10.11

---

sbcl/patch-float-state-saving.diff

Ticket: https://bugs.launchpad.net/sbcl/+bug/1678347
Upstream commit: https://sourceforge.net/p/sbcl/sbcl/ci/075f1de45cd2b142c739ef5d56bbb1cc7ffe9a07/

sbcl: fix CI build for 1.3.16

---

openblas/openblas0.2.19.diff

See
https://github.com/xianyi/OpenBLAS/pull/982

openblas: patch for llvm 3.9

---

miniupnpc/CVE-2017-8798.diff

miniupnpc: add patch for CVE-2017-8798

---

LICENSE

license: tweaks

---

qt5/QTBUG-56814.patch

https://bugreports.qt.io/browse/QTBUG-56814

qt5: Workaround for macdeployqt tool

---

nanopolish/nanopolish.patch

PR opened upstream, see
https://github.com/jts/nanopolish/pull/154

nanopolish: patch for compilation

---

enblend-enfuse/enblend-enfuse-4.2.patch

Adds missing files in the release tar file
https://bugs.launchpad.net/enblend/+bug/1568917

enblend-enfuse: patch for version 4.2

---

optipng/optipng-10.13-st_atim.patch

https://github.com/Homebrew/homebrew-core/pull/15419

optipng: patch for 10.13

---

wine/2.14.patch

https://github.com/Homebrew/homebrew-core/pull/16372

wine: patch for screen-flickering issues

---

ffmpeg/openjpeg-2.2.patch

Corresponds to upstream commit https://github.com/FFmpeg/FFmpeg/commit/078322f33ced4b2db6ac3e5002f98233d6fbf643

ffmpeg: patch for openjpeg 2.2 compatibility

---

emscripten/emscripten-resolve-symlinks.patch

https://github.com/Homebrew/homebrew-core/pull/17275.

emscripten: patch for kripken/emscripten#5534

---

povray/patch-lseek64.diff

update patch-lseek64.diff for 3.7.0.3

povray: update patch-lseek64.diff for 3.7.0.3

---

povray/patch-vfe-uint.diff

update header include patch to apply cleanly

povray: update header include patch to apply cleanly

---

povray/patch-unix-configure.ac.diff

update unix configure.ac patch

povray: update unix configure.ac patch

---

povray/compiler-warnings.diff

refactor upstream commit to fix compiler warnings
upstream - https://github.com/POV-Ray/povray/commit/b3846f57237

povray: refactor upstream commit to fix compiler warnings

---

povray/boost-1.65.0.diff

Adapted from https://github.com/POV-Ray/povray/pull/318.
CC @fxcoudert @JCount

povray: boost 1.65.0 compatibility

---

faac/clang-compatibility-fix.patch

https://sourceforge.net/p/faac/faac/ci/4036f2c85038ef199a4636a6cbc4448f5e914d39/tree/libfaac/quantize.c?diff=985311eadee3fd9e5624014cc3ff58917c989d78

faac: upstream clang compatibility fix

---

knot-resolver/fix-loading-modules-on-Darwin.diff

Created from:
https://gitlab.labs.nic.cz/knot/knot-resolver/commit/16d5d5de480

knot-resolver: fix loading modules on Darwin

---

iozone/bzero.patch

iozone: patch to use memset instead of bzero

---

vcdimager/libcdio-1.0-compat.diff

https://savannah.gnu.org/support/index.php?109421

vcdimager: patch for libcdio 1.0 compatibility

---

qt/QTBUG-65075.diff

Equivalent to https://codereview.qt-project.org/#/c/213993/
Fixes https://bugreports.qt.io/browse/QTBUG-65075

qt: add patch for QTBUG-65075

---

qtads/xcode9.diff

qtads: add patch for Xcode 9

---

shogun/fix_python_linking.patch

there was a part missing from the cut out patch for the python linking problem

add missing patch for shogun

---

f3/argp_flags.diff

https://github.com/AltraMayor/f3/commit/5ad4130088f183e61ba90ff38af1eca614d89eb2
cc @ilovezfs

f3: add patch for argp-standalone flags

---

geeqie/wexitstatus_fix.diff

https://github.com/BestImageViewer/geeqie/pull/589
cc @ilovezfs

Add geeqie 1.4 patch

---

geckodriver/bug-1435830.patch

See https://github.com/Homebrew/homebrew-core/pull/24802, https://bugzilla.mozilla.org/show_bug.cgi?id=1441204.

geckodriver: fix bug 1436830

---

cloog/cloog-isl0.19-compat.diff

https://github.com/Homebrew/homebrew-core/pull/25107

cloog: isl 0.19 compatabilty

---

fribidi/fix-docs.diff

Remove for > 1.0.2
https://github.com/fribidi/fribidi/commit/095d88503194e81059ab81d04b849d9245899dfa
https://github.com/fribidi/fribidi/issues/72

fribidi: patch to fix docs

---

radare2/fix_openssl_build.patch

https://github.com/radare/radare2/pull/10188

radare2: fix build with openssl

---

gdb/python37.diff

https://sourceware.org/bugzilla/show_bug.cgi?id=23252
https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;h=863d5065467b16304f6b5c80a186e3bcc68c48a6

gdb: add patch for Python 3.7

---

geeqie/exiv2_fix.diff

Backported from https://github.com/BestImageViewer/geeqie/pull/655

geeqie: add patch for exiv2 0.27

---

meson/xcode_11.patch

Backported from https://github.com/mesonbuild/meson/commit/b28e76f6bf6898a7de01f5dd103d5ad7c54bea45

meson: add Xcode 11 patch

---

python@2/clt-sdk-path-lookup.patch

https://bugs.python.org/issue37285
Taken from https://github.com/python/cpython/pull/14095

python@2: add CLT SDK lookup patch

---

john/1.9.0.patch

Backport of official patch from jumbo fork (https://www.openwall.com/lists/john-users/2016/01/04/1)

john: add patch for 1.9.0

---

shellinabox/2.20.patch

This combines the 7 individual commits in https://github.com/shellinabox/shellinabox/pull/467, while resolving several "already-patched" rejections in one of them.
In support of https://github.com/Homebrew/brew/pull/8075

shellinabox: 2.20 patch rollup

---

squashfs/4.4.patch

In support of https://github.com/Homebrew/brew/pull/8075
Source: https://patch-diff.githubusercontent.com/raw/plougher/squashfs-tools/pull/69.patch?full_index=1

squashfs 4.4: rollup patch

---

tfenv/2.0.0.patch

In support of https://github.com/Homebrew/brew/pull/8075
Original source: https://patch-diff.githubusercontent.com/raw/tfutils/tfenv/pull/181.patch?full_index=1

tfenv 2.0.0: rollup patch

---

fontforge/20200314.patch

Original patchset: https://github.com/fontforge/fontforge/pull/4258.patch?full_index=1
In support of https://github.com/Homebrew/brew/pull/8075

fontforge 20200314: patch rollup

---

gpsbabel/1.7.0.patch

Patch for https://github.com/Homebrew/homebrew-core/pull/57721
Contains commits from https://github.com/gpsbabel/gpsbabel/pull/611
@gromgit - does this look okay?

gpsbabel: patch for 1.7.0

---

liblinear/patch-Makefile.diff

Needed for https://github.com/Homebrew/homebrew-core/pull/58498.

liblinear: patch for 2.40

---

libsoxr/arm64_defines.patch

Filed upstream: https://sourceforge.net/p/soxr/code/merge-requests/5/

libsoxr: patch for Apple silicon

---

libvidstab/fix_cmake_quoting.patch

Upstream PR: https://github.com/georgmartius/vid.stab/pull/93

libvidstab: add patch to fix cmake quoting

---

dieharder/dieharder-linux.patch

See
https://aur.archlinux.org/cgit/aur.git/tree/stdint.patch?h=dieharder

dieharder: add patch for linux

---

openjdk@8/xcode.patch

https://github.com/Homebrew/homebrew-core/pull/63689

openjdk@8: patch for Xcode 11+

---

groff/1.22.4.patch

See https://github.com/Homebrew/homebrew-core/pull/65042

groff: patch 1.22.4 for Xcode 12

---

ocaml/arm64-4.10.patch

Taken from https://github.com/ocaml/ocaml/pull/10026 after confirming that after applying @EduardoRFS’s patch, `brew install -s ocaml` builds and runs fine, and passes `brew test`.

ocaml: add 4.10 arm64 patch

---

libav/remove_unconditional_X11_probe.patch

Supports https://github.com/Homebrew/homebrew-core/pull/65345

libav: add patch to remove auto X11 probing

---

mapnik/mapnik-2.0.23.patch

see:
https://github.com/mapnik/mapnik/issues/4196

mapnik: fix for boost 1.74.0

---

vsftpd/3.0.3.patch

Just some hand-tweaking of the patch

vsftpd: tweak library detection further for Big Sur

---

python/3.7.9.patch

Needed for https://github.com/Homebrew/homebrew-core/pull/68528

python: backport Big Sur support for Python 3.7

---

urweb/icu4c68-2.patch

Supports
https://github.com/Homebrew/homebrew-core/pull/71274

urweb: add patch for icu4c 68.2

---

mariadb/mariadb-10.5.8-apple-silicon.patch

As requested in https://github.com/Homebrew/homebrew-core/pull/70060#issuecomment-773376928

mariadb: patch for 10.5.8 for Apple Silicon

---

glib/hardcoded-paths.diff

Necessary for https://github.com/Homebrew/homebrew-core/pull/73426

glib 2.68.0: fix patch

---

freeimage/3.17.0-linux.patch

This is an equivalent to the mac patch,
taken from:
https://gist.githubusercontent.com/davydden/5a4f348108d3c9110299/raw/3396840ff71c639d848ce552de9124462777ab97/freeimage.patch

freeimage: add linux patch

---

john-jumbo/john_jumbo_m1.diff

Ref: https://github.com/Homebrew/homebrew-core/pull/75208

john-jumbo: add ARM64/Apple Silicon patch

---

opencv@3/tbb2021.patch

This is needed for https://github.com/Homebrew/homebrew-core/pull/77662.

opencv@3: add patch for tbb2021

---

lanraragi/tempdir.patch

This is a backport of https://github.com/Difegue/LANraragi/commit/aeb9e6dac7d4f9c402540dbdb2c5245583df2196.
See Homebrew/homebrew-core#78466.

lanraragi: add patch to fix test

---

lua/lua-so.patch
lua@5.1/lua-so.patch
lua@5.3/lua-so.patch

Equivalent to the macOS patches to build .dylib files

lua@x: add patches to build .so files on Linux

---

lua/lua-so.patch

lua: add path changes to linux patch

---

ccextractor/unbundle-libs.patch

ccextractor: unbundle libs

---

global/6.6.7-external-sqlite.patch

Supports https://github.com/Homebrew/homebrew-core/pull/81424

global: enable external SQLite

---

lua/lua-so.patch

Trying out patch change to see if linkage in https://github.com/Homebrew/homebrew-core/pull/81151

lua: change order of -ldl in Linux patch

---

libgsm/libgsm_shared_mac.patch

libgsm_shared_mac.patch: fix header

---

vault/1.8.2.patch

relates to Homebrew/homebrew-core#84092
Source, https://patch-diff.githubusercontent.com/raw/hashicorp/vault/pull/12358.patch

vault: add 1.8.2 build patch

---

gdbm/fix-st_mtim.diff

https://github.com/Homebrew/homebrew-core/pull/85852

gdbm: add patch for st_mtim/st_mtimespec

---

pygit2/libgit2-1.3.0.patch

Adapted from https://github.com/libgit2/pygit2/commit/df8c204873bd37d6e323017c48982a27a4557c28.
Supports Homebrew/homebrew-core#86100.

Update PyGit2 patch for libgit2 1.3.0

---

uncrustify/uncrustify-0.73.0.patch

see discussion in https://github.com/Homebrew/homebrew-core/pull/86327
@carlocab

uncrustify: add build fixes for 0.73.0 from later PRs

---

vsftpd/3.0.5.patch

Fixes https://github.com/Homebrew/homebrew-core/issues/88570

vsftpd 3.0.5 patch for Monterey (fixes non-existing setrlimit syscall)

---

usbutils/portable.patch

Upstream PR: https://github.com/gregkh/usbutils/pull/134
Needed for: https://github.com/Homebrew/homebrew-core/pull/89341

usbutils: make buildable and runnable on macOS.

---

yle-dl/20220213.patch

Backport of https://github.com/aajanki/yle-dl/commit/5f3b6246213b76fb0af60eef96caabbb5141d615
For https://github.com/Homebrew/homebrew-core/pull/100048

yle-dl: patch for 20220213

---

qt5/qt5-webengine-chromium-python3.patch
qt5/qt5-webengine-gcc12.patch
qt5/qt5-webengine-python3.patch

I am putting these patches for Python 3 support here for now until this has been upstreamed.

qt5: add python 3 and GCC 12 support

---

qt5/qt5-webengine-chromium-python3.patch

Fix a mistake in committed patch.

fix qt5-webengine-chromium-python3.patch

---

mesa/fix-build-on-macOS.patch

Signed-off-by: Yurii Kolesnykov <root@yurikoles.com>

add patch for mesa 22.1.x build regression

---

mysql/boost-check.patch
percona-server/boost-check.patch

See Homebrew/homebrew-test-bot#820.

Patch out `boost` check in `mysql` build.

---

netcdf/netcdf-json.diff

From https://github.com/Unidata/netcdf-c/pull/2448
Part of https://github.com/Homebrew/homebrew-core/pull/112159

netcdf: patch for json conflict

---

dotnet/aspnetcore-version.patch

https://github.com/Homebrew/homebrew-core/pull/115365

dotnet: backport patch to stop overriding aspnetcore version

---

waffle/meson-fix-macOS-typo.patch

Signed-off-by: Yurii Kolesnykov <root@yurikoles.com>

waffle: fix build on macOS by fixing a typo

---

opencv/gapi-openvino-api2.0.patch
opencv/openvino-api2.0.patch

This patch for OpenCV DNN module to work with OpenVINO 2024.0.0

opencv: patch for DNN module using openvino 2024.0.0

---

chcase/2.0.patch

This PR will remove an unused directory

Delete chcase directory

---

or-tools/abseil-vlog-is-on.patch

PR https://github.com/google/or-tools/pull/4339 does not apply cleanly.

or-tools: add patch for abseil 20240722.0

---

usbutils/portable.patch

- Updated for Meson
- Added options to not build sysfs and udev code.
- Applied some suggestions for Greg in an old upstream PR https://github.com/gregkh/usbutils/pull/134
- Tree mode is not supported and should not be built.
- Forked `names.c` to `names_no_udev.c` for non udev version.
- Added explicit dep on `iconv`.
```bash
$ lsusb --version
lsusb (usbutils) 018
```
```bash
$ lsusb
Bus 000 Device 001: ID 2972:0047
```
```bash
$ lsusb -v
```
<details>
<summary>Output:</summary>
```
Bus 000 Device 001: ID 2972:0047  
Negotiated speed: High Speed (480Mbps)
Device Descriptor:
bLength                18
bDescriptorType         1
bcdUSB               2.00
bDeviceClass          239 [unknown]
bDeviceSubClass         2 [unknown]
bDeviceProtocol         1 
bMaxPacketSize0        64
idVendor …
```

usbutils: update portable.patch (usbutils 018)

---

dhall-lsp-server/ghc-9.6.patch

https://github.com/dhall-lang/dhall-haskell/commit/d7a024e1ff87b89a64e51699e3f609fd4a719451
---
Can after checking CI in https://github.com/Homebrew/homebrew-core/pull/203239

dhall-lsp-server: patch for GHC 9.6

---

sigma-cli/pysigma-0.11.19-poetry-2.0.patch

relates to SigmaHQ/pySigma#318
relates to https://github.com/Homebrew/homebrew-core/pull/204989

sigma-cli: add poetry 2.0 build patch for pysigma 0.11.19

---

stella/7.0c-ventura.patch

- https://github.com/stella-emu/stella/pull/1064
- https://github.com/Homebrew/homebrew-core/pull/205268

stella: revert `Convert stringstream::view()` to `stringstream::str()` for ventura builds

---

curlpp/curl-8.10.patch

relates to:
- https://github.com/jpbarrette/curlpp/pull/171

curlpp: add curl 8.10 build patch

---

cargo-release/0.25.17-libgit2-1.9.patch

https://github.com/Homebrew/homebrew-core/pull/218323

cargo-release: add libgit2 1.9 patch for 0.25.17 build

---

loki/loki-3.5.1-purego.patch

- https://github.com/grafana/loki/pull/17807
- https://github.com/Homebrew/homebrew-core/pull/224454

loki: add purego patch for 3.5.1 release

---

bedops/2.4.42-debian.patch

- https://github.com/Homebrew/homebrew-core/pull/219872

bedops: update debian patch for 2.4.42 release

---

gcc/gcc-13.4.0.diff

From the branch at https://github.com/iains/gcc-13-branch

gcc: patch for 13.4.0

---

irrlicht/use-system-libs.patch
irrlicht/xcode.patch
movgrab/libUseful_xattr_backport.diff
openssh/patch-sandbox-darwin.c-apple-sandbox-named-external.diff

(I am gonna write some script to automate the removal later)
- #1020

restore patches which are still in use

---

action-validator/0.6.0-rust-1.87.patch

- https://github.com/Homebrew/homebrew-core/pull/223613
- https://github.com/Homebrew/homebrew-core/actions/runs/15055542156/job/42331830563#step:3:1731

action-validator: add rust 1.87.0 patch

---

swift/llbuild-sqlite3.patch

For Swift 6.2
https://github.com/Homebrew/homebrew-core/pull/245341/files#diff-363bc2d39e523bd3f024f750b11c039706d59cd94be0c367362d47f6e31d54edR155

swift: update llbuild patch

---

swift/llbuild-sqlite3.patch
swift/swiftpm-sqlite3.patch

swift: update patches for Swift 6.2
