Homebrew/formula-patches

rubberband/rubberband-1.8.1-yosemite.diff
per https://github.com/Homebrew/homebrew/pull/48775
taken from https://webcache.googleusercontent.com/search?q=cache:http://tuohela.net/irc/rubberband-1.8.1-yosemite.diff
=> rubberband-1.8.1 patch

libspatialite/sqlite310.patch
Equivalent upstream patch:
https://www.gaia-gis.it/fossil/libspatialite/info/bf5bd8b1ba
https://www.gaia-gis.it/fossil/libspatialite/vpatch?from=aa408ed10d384f46&to=bf5bd8b1ba3981f0
https://github.com/Homebrew/homebrew/pull/49680
=> libspatialite: upstream patch for >=sqlite 3.10

openssl/revert-pass-pure-constants-verbatim.patch, openssl/tshort-asm.patch
This replicates Clemens Lang's work for MacPorts.
https://github.com/ryandesign/macports-ports/commit/5522f4c5b202436d6f9787cce417b1c5619cea1b
Quoting him,
Reverts openssl's upstream commit
openssl/openssl@fd7dc20
and applies an alternative suggested in a pull request at
openssl/openssl#597
that would merge
akamai/openssl@c4af68c
=> openssl: Fix on 10.6

tinyscheme/patch-makefile.diff
Earlier patch (#18) had git-style location information, causing it to fail with -p0.
Sorry for the foul-up.
cc @DomT4
=> tinyscheme: fix patch

gperftools/revert-sized-delete-aliases.patch
Reverts upstream commit
build sized delete aliases even when sized-delete is disabled
https://github.com/gperftools/gperftools/commit/782165fa7f2c49d6a67c2415626a1f215cc21ac2
Prevents
```
Undefined symbols for architecture x86_64:
"operator delete(void*, unsigned long)", referenced from:
ProcMapsIterator::~ProcMapsIterator() in libsysinfo.a(sysinfo.o)
ProcMapsIterator::~ProcMapsIterator() in libsysinfo.a(sysinfo.o)
tcmalloc::FillProcSelfMaps(char*, int, bool*) in libsysinfo.a(sysinfo.o)
tcmalloc::DumpProcSelfMaps(int) in libsysinfo.a(sysinfo.o)
```
Workaround for https://github.com/gperftools/gperftools/issues/794
See Homebrew/homebrew-core#383.
=> gperftools: prevent operator delete build failure

prettyping/ipv6.patch
OS X/BSD ping has slightly different output when doing IPv6 compared to GNU/ping.
This is a partial from denilsonsa/prettyping#11.
=> prettyping: Add patch to fix IPv6 parsing

sane-backends/1.0.25-missing-types.patch
from https://github.com/Homebrew/homebrew-core/pull/2467
=> add sane-backends/1.0.25-missing-types.patch

cocoapods/patch-activesupport-4.x.diff
Avoids use of activesupport version 5 (which requires Ruby >= 2.2.2).
https://github.com/CocoaPods/CocoaPods/pull/5602
https://github.com/CocoaPods/CocoaPods/commit/c6e557b
=> cocoapods: patch for avoiding activesupport 5

valgrind/10.11_assertion.diff
The old patch doesn't really apply on 3.11.0, and the offending part is `NEWS` which hardly carries any value. Just remove that part.
=> valgrind: fix 10.11 assertion patch

valgrind/xcode-8.diff
From svn r15949. See https://bugs.kde.org/show_bug.cgi?id=366138#c5.
=> valgrind: patch for Xcode 8

wxmac/patch-quicktime-removal.diff, wxmac/patch-yosemite.diff
- `patch-yosemite.diff`: Old patch, pulled out from `__END__` in the formula;
- `patch-quicktime-removal.diff`: Required for building against Xcode 8 (with macOS 10.12 SDK, where `<QuickTime/QuickTime.h>` has been removed).
Ref http://trac.wxwidgets.org/changeset/f6a2d1caef5c6d412c84aa900cb0d3990b350938/git-wxWidgets
=> wxmac: patches

purescript/purescript-optparse-applicative.patch
This patch can be removed when 0.10.0 is released.
See https://github.com/purescript/purescript/pull/2278.
Same as upstream https://github.com/purescript/purescript/commit/bdbf4e2
except that the change to the CONTRIBUTORS file has been removed since
it did not apply cleanly.
=> purescript: add optparse-applicative patch

diffoscope/patch-legacy-diff.diff
https://anonscm.debian.org/cgit/reproducible/diffoscope.git/patch/?id=261be7
Existing patch in `diffoscope.rb`. Host it so that cgit update won't break our checksum.
=> diffoscope: patch for legacy diff(1)

glib/gnotification-mountain.patch
Applying the old patch fails with [glib 2.50.0](https://github.com/Homebrew/homebrew-core/pull/5109). I made this new patch by looking at each change in the old patch and making a corresponding change to the updated glib sources. Now the build succeeds on 10.7.5.
I'm about to make a pull request to the [glib formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/glib.rb), where I intend to use my personal formula-patches fork as the source for the updated patch, expecting that the URL will be updated later (if the changes are accepted). This is my first time editing a formula patch, so I hope my approach is not terribly wrong.
=> glib: 2.50.0 (Mountain) Lion patch update

qt5/qtconnectivity-bluetooth-fix.diff, qt5/qtwebengine-bluetooth-fix.diff
CoreBluetooth headers now need to be imported.
The qtconnectivity patch is an upstream commit, while the qtwebengine
patch was contributed by Steve Yin. Both patches are basically the same
fix, just in two different modules of the Qt 5 code base.
=> qt5: bluetooth fixes

qscintilla2/xcode-8.patch
This patch is the work of Alan Garnyfrom.
Same as opencor commit "QScintilla: fix Xcode 8 compilation problem."
https://github.com/opencor/opencor/commit/70f3944e36b8b95b3ad92106aeae2f511b3f0e90
=> qscintilla2: better Xcode 8 patch

qt5/xcrun-xcode-8.patch
Upstream commit from 7 Jul 2016 "configure and mkspecs: Don't try to find xcrun with xcrun"
http://code.qt.io/cgit/qt/qtbase.git/patch/configure?id=77a71c32c9d19b87f79b208929e71282e8d8b5d9
=> qt5: xcrun fix for Xcode 8

qt5/qt3d-parallel-build-fix.patch
Upstream commit from 4 Aug 2016 "Fixes parallel builds where they were
sometimes failing on macOS with static builds."
http://code.qt.io/cgit/qt/qt3d.git/commit/src/src.pro?id=db3baec236841f9390e9450772838cb7ba878069
=> qt5: qt3d parallelized build fix

qt5/qtwebengine-bluetooth-fix.diff
minor change so that it can be applied successfully to the 5.7.0 sources
=> qt5: qtwebengine bluetooth fix refresh for 5.7.0

qt5/cups-sierra.patch
Equivalent to upstream commit from 4 Oct 2016 "Fix CUPS compilation error in macOS 10.12"
http://code.qt.io/cgit/qt/qtwebengine-chromium.git/commit/chromium/printing/backend/print_backend_cups.cc?h=53-based&id=3bd01037ab73b3ffbf4abbf97c54443a91b2fc4d
https://codereview.chromium.org/2248343002
=> qt5: CUPS build fix for Sierra

allegro/patch-allegro-10.12.diff
https://github.com/liballeg/allegro5/pull/682
(Cannot use the patch directly because `.travis.yml` is not in the release tarball.)
=> allegro: patch for 10.12

swift/swift-2.2.1-pod2man.patch
Patch picked from `swift` upstream at https://github.com/apple/swift/commit/4e291f0b09d8bb86c91d608c1f52d741fd971527.
Needed to fix build errors in swift 2.2.1 against some versions of `pod2man`; see https://github.com/Homebrew/homebrew-core/issues/5306.
=> swift: fix build with newer pod2mans

graph-tool/add-degree-to-filtered-graph.diff
graph-tool isn't using the stock filtered_graph.hpp, so its modified
header needs the same change that was made in boost 1.62.0 adding an
implementation of the 'degree' function for filtered_graph
=> graph-tool: boost 1.62.0 fix

qt5/widget-examples.patch
Upstream commit "Add install target to mac widget examples"
http://code.qt.io/cgit/qt/qtbase.git/commit/examples/widgets/mac/qmaccocoaviewcontainer/qmaccocoaviewcontainer.pro?h=5.7&id=58408ffa1b9c0b42a1719d3c8a4d4c62dec4fce6
=> qt5: fix for widget examples' missing install target

spades/jemalloc-sierra-fix.diff
This fix is already in the latest release of jemalloc, but hasn't made
its way over to the vendored version of jemalloc in SPAdes yet.
=> spades: jemalloc Sierra fix

osquery/patch-gflags-2.2.0.diff
Same as upstream PR "[Fix #2798] Update gflags on OS X/Linux to 2.2.0"
except for the changes to the upstream gflags and glog formula files,
which don't yet exist in osquery 1.7.3, the current version in core
=> osquery: patch for gflags 2.2.0 compatibility

xplanet/xplanet-1.3.1-ntimes.patch
to resolve `-num_times=2` bug
Per https://github.com/Homebrew/homebrew-core/pull/7372
=> xplanet 1.3.1 patch

ucspi-tcp/patch-0.88-ipv6.diff
Originally https://www.fefe.de/ucspi/ucspi-tcp-0.88-ipv6.diff19.bz2. fefe.de has since disappeared from the Internet.
The current version was downloaded from https://web.archive.org/web/20160403064123/http://www.fefe.de/ucspi/ucspi-tcp-0.88-ipv6.diff19.bz2, then bunzip2'ed. The checksum of the bz2 archive, 35952cd290d714452c840580126004cbae8db65b1632df67ac9c8fad7d1f9ace, matches the documented checksum already in use.
=> uscpi-tcp: vendor IPv6 patch

blast/blast-make-fix2.5.0.diff
This patch has been provided by upstream and is already merged
for release 2.6.0. Without it the installation will fail.
=> blast: MakeFile patch (2.5.0)

vtk/vtk-nopythonlinking-7.1.0.patch
This patch has been submitted upstream:
https://gitlab.kitware.com/vtk/vtk/merge_requests/1713
The version in this commit is a backport from
the patch, as there are some slight differences
between the current VTK master and VTK 7.1.0,
which is the latest stable version.
See https://github.com/Homebrew/homebrew-science/pull/3811 for ref.
=> vtk: patch to prevent linking against python

qt5/QTBUG-57656.patch
Without this patch, none of the QtDesigner plugins (e.g. from KDE Frameworks 5) will build.
Patch taken from https://codereview.qt-project.org/#/c/184053/1
=> Patch for QTBUG-57656

simutrans/avfoundation.patch
Submitted upstream here: http://forum.simutrans.com/index.php?topic=16675
Required to build on 10.12, since QTKit is no longer in the SDK.
cc @ilovezfs
=> simutrans: add AVFoundation patch

paraview/paraview-5.2.0-hdf5.diff
This will allow to use system hdf5 and system netcdf.
Patch has been merged upstream and will be in the next release.
See https://gitlab.kitware.com/vtk/vtk/commit/0e25e61caf07f4ed87a748b2cdc5648649a6ef42
The patch can be applied to the VTK that is internally built by Paraview.
=> paraview: patch for hdf5 1.10.0

gnupg21/ssh-import-scm.patch
=> gnupg21: patch for "make check" on 10.10 and below

med-file/libc++_and_python_bindings_fixes.diff
Reference: Homebrew/homebrew-science#5138
=> med-file: Patches to enable building with Apple's clang libc++

go@1.4/go@1.4-Sierra-build.patch
primarily addresses issues regarding the changed behavior of Sierra's gettimeofday function
=> go@1.4: patch to fix building on macOS Sierra

go@1.5/go@1.5-Sierra-build.patch
primarily addresses issues regarding the changed behavior of Sierra's gettimeofday function
=> go@1.5: patch to fix building on macOS Sierra

go@1.6/go@1.6-Sierra-build.patch
primarily addresses issues regarding the changed behavior of Sierra's gettimeofday function
=> go@1.6: patch to fix building on macOS Sierra

gnupg/agent-handle-scdaemon-errors.patch
upstream commit "agent: For SSH, robustly handling scdaemon's errors."
https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git;a=patch;h=4ce4f2f683a17be3ddb93729f3f25014a97934ad
See https://bugs.gnupg.org/gnupg/issue2980
=> gnupg: add patch for agent's handling of scdaemon errors

gnupg/fix-using-tools-from-build-dir.patch
Lets us run "make check" before "make install".
upstream commit "tests: Fix using tools from the build directory."
https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git;a=patch;h=a98459d3f4ec3d196fb0adb0e90dadf40abc8c81
See https://bugs.gnupg.org/gnupg/issue2979
=> gnupg: add patch for using tools from the build directory

dirmngr/D186.diff
As it is no longer available from the GNU bugtracker, we need to provide it ourselves.
See https://github.com/Homebrew/homebrew-core/issues/12001
=> dirmngr: Add patch for dirmngr

nano/configure-ignore-reg-enhanced-test.diff
Upstream commit adapted to apply to configure instead of configure.ac.
See https://savannah.gnu.org/bugs/index.php?50714.
```
commit cc91ee603c24429375ace5d4b55d85c396668c2e
Author: Mike Frysinger <vapier@gentoo.org>
Date:   Tue Apr 4 12:42:23 2017 -0400
configure: ignore the REG_ENHANCED test when we use gnulib
If we're using the bundled gnulib regex module, then assume REG_ENHANCED
is not supported (since gnulib doesn't support it).
This fixes https://savannah.gnu.org/bugs/?50714.
```
=> nano: add patch for configure to ignore the REG_ENHANCED test

nano/configure-fix-up-word-boundary-regex-logic.diff
Upstream commit adapted to apply to configure instead of configure.ac.
See https://savannah.gnu.org/bugs/?50705.
```
commit 8f2b5bbf3d1b23007aedc9f07f224da91f0ec479
Author: Mike Frysinger <vapier@gentoo.org>
Date:   Mon Apr 3 15:10:53 2017 -0400
configure: fix up word boundary regex logic now that we have gnulib
If we're using the bundled gnulib regex module, then assume word boundary
support is available to avoid issues with the regcomp test.  This also
unifies the different code paths a bit.
This fixes https://savannah.gnu.org/bugs/?50705.
```
=> nano: add patch for configure to fix up word boundary regex logic

cmake/cmake-3.7.2-lto_library.diff, cmake/cmake-3.8.0-rc4-lto_library.diff
See https://gitlab.kitware.com/cmake/cmake/issues/16766
Backports of https://gitlab.kitware.com/cmake/cmake/commit/53f17333f830d4f314bbe10ba32889bbcfbc3c46
```
Commit 53f17333
authored 3 days ago by Brad King's avatar Brad King
CMakeParseImplicitLinkInfo: Ignore ld -lto_library flag
The `ld` tool in Xcode 8.3 now has a `-lto_library <path>` flag.  Ignore
the flag instead of accidentally parsing it as `-l` with `to_library`.
Fixes: #16766
```
=> cmake: patches for -lto_library bug for 3.7.2 and 3.8.0-rc4

osquery/patch-thrift-0.10.diff
upstream osquery comment on the thrift patch is "Special case because we
expect setuid syscalls in other threads"
=> osquery: patch for thrift 0.10

qt5/QTBUG-58344.patch
Upstream issue QTBUG-58344 "UI crash upon start" which won't be fixed in qt 5.7, 5.8.
Affected at least a formula djview4.
Patch is created with non-essential changes from the upstream patch.
See https://codereview.qt-project.org/#/c/183183/
=> qt5: Add patch to fix QT-58344

node@0.12/v8-xcode-8.3.diff
Fixes build failure with >= Apple LLVM version 8.1.0 (clang-802.0.42).
The error is
```
../deps/v8/include/v8.h:5800:54: error: 'CreateHandle' is a protected member of 'v8::HandleScope'
```
Fix suggested by Thomas Rosenstein in https://github.com/nodejs/node-gyp/issues/1160.
=> node@0.12: fix for Xcode 8.3

riemann-client/alias-fix.diff
reverts upstream commit "Rearrange symbol versioning and aliases"
See
https://github.com/algernon/riemann-c-client/commit/434f820d3c951067cea46a191bbc0dc80ec107b0
https://github.com/algernon/riemann-c-client/issues/18
https://github.com/algernon/riemann-c-client/issues/19
https://github.com/Homebrew/homebrew-core/pull/14437
=> riemann-client: fix alias build error

zsh/fix-autocomplete.patch
Upstream commit "40305: fix some problems redisplaying command line
after"
https://github.com/zsh-users/zsh/commit/34656ec2f00d6669cef56afdbffdd90639d7b465
The patch won't be needed once zsh 5.3.2 ships.
=> zsh: patch for autocomplete

gst-plugins-bad/gstglwindow_cocoa.patch
This header was not shipped in the 1.12.1 release. The issue was fixed
upstream already with this commit:
https://cgit.freedesktop.org/gstreamer/gst-plugins-bad/patch/?id=450b1c92abe2ae8f84e557f61c9512a1f4006bab
=> gst-plugins-bad: new patch adding the gstglwindow_cocoa.h file

graph-tool/chrono-disambiguation.diff
Added in reference to [this request](https://github.com/Homebrew/homebrew-science/pull/5242#pullrequestreview-25712861) by @iMichka.
=> graph-tool: add patch to fix compilation error regarding ambiguous chrono with boost 1.63

erlang@18/boring-ssl-high-sierra.patch, erlang@19/boring-ssl-high-sierra.patch
Backports of https://github.com/erlang/otp/pull/1501 to maint-18 and maint-19.
=> erlang@19 and erlang@18: patches for BoringSSL on 10.13

erlang@17/boring-ssl-high-sierra.patch
=> erlang@17: add patch for BoringSSL on 10.13

poppler/clang.diff
Add user-provided default constructor for AttributeDefaults.
Avoids the following build failure:
```
CXX      libpoppler_la-StructElement.lo
StructElement.cc:264:32: error: default initialization of an object of const type
'const AttributeDefaults' without a user-provided default constructor
static const AttributeDefaults attributeDefaults;
^
{}
1 error generated.
make[3]: *** [libpoppler_la-StructElement.lo] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```
=> poppler: fix build with clang

poppler/clang.diff
The patch was accepted upstream in https://cgit.freedesktop.org/poppler/poppler/commit/?id=dd80c182cbcb188af0dd590f222ba9bbb31e3fb7.
See https://bugs.freedesktop.org/show_bug.cgi?id=102538.
=> poppler: update clang fix to use upstream patch

bonnie++/remove-large-file-support-macros.diff
The large file support part of the patch from
https://github.com/Homebrew/legacy-homebrew/pull/35764
The rest of the changes from that patch have already been upstreamed.
=> bonnie++: remove the _LARGEFILE64_SOURCE macros

iozone/mythread_create.diff
Addresses the following build failure, which affects iozone > 3.459:
```
iozone.c:18963:1: error: conflicting types for 'mythread_create'
mythread_create( void *(*func)(void *),int x)
^
iozone.c:1046:11: note: previous declaration is here
long long mythread_create( void *, int );
```
=> iozone: fix for conflicting types for mythread_create

enigma/c++11.patch
Correct broken implicit conversions which no longer work with a C++11 compiler.  Required to build with Xerces-C 3.2.0 and C++11.
See https://github.com/Enigma-Game/Enigma/pull/8
=> enigma: Compile with a C++11 compiler

xml-security-c/c++11.patch
Correct broken implicit conversions which are forbidden with C++11. Required to build with Xerces-C 3.2.0 and C++11.
See https://issues.apache.org/jira/browse/SANTUARIO-471
=> xml-security-c: Compile with a C++11 compiler.

xqilla/xerces-containing-node.patch
Xerces-C 3.1 provided non-portable and unsafe casts which were replaced with a safe alternative in 3.2.0.  This patch is required to build with Xerces-C 3.2.0.
See https://sourceforge.net/p/xqilla/bugs/48/
=> xqilla: Use new Xerces 3.2.0 containing node introspection

dbxml/c++11.patch
Required to build with Xerces-C 3.2.0 with C++11.
Unfortunately, Oracle don't provide an upstream mailing list or bugtracker accessible to non-paying customers, so the patch can't be submitted upstream.
=> dbxml: Compile with a C++11 compiler

exiftran/fix-build.diff
initial config patch after rename from fbida
Goes with https://github.com/Homebrew/homebrew-core/pull/17901
=> exiftran: initial config patch after rename from fbida

blast/blast2.6.0-ver2.diff
Upstream did not make a new release but provided a patch,
and call this version "ver2"
Instead of getting the patch from upstream,
it is better that we host it ourselfs.
=> blast: 2.6.0 ver2 patch

cvs/vasnprintf-high-sierra-fix.diff
Fixes error: Illegal instuction 4
%n used in a non-immutable format string
=> cvs: fix runtime error on 10.13 caused by gnulib vasnprintf

vte3/fix-strchrnul.patch
vteseq.cc:2537:18: error: use of undeclared identifier 'strchrnul'
Patch adapted from https://bugzilla.gnome.org/show_bug.cgi?id=788476
to avoid Autotools deps.
=> vte3: fix for strchrnul

icu4c/CVE-2017-14952.diff
Upstream commit from 9 Aug 2017 "Removed redundant UVector entry clean up function call"
http://bugs.icu-project.org/trac/ticket/13302
http://bugs.icu-project.org/trac/changeset/40324/trunk/icu4c/source/i18n/zonemeta.cpp
=> icu4c: add patch for CVE-2017-14952

hashcat/VERSION_TAG.patch
See https://github.com/hashcat/hashcat/issues/1412 and https://github.com/hashcat/hashcat/pull/1413.
=> hashcat: add patch for VERSION_TAG in Makefile

git-cinnabar/mercurial-4.4-sshpeer.patch
Backport of https://github.com/glandium/git-cinnabar/commit/5c59ae1baaeb1585f3c1f3a4cb63a2e03fa213a4 to git-cinnabar 0.4.0
=> git-cinnabar: backport mercurial 4.4 sshpeer patch

opencbm/endian.diff
Use libkern/OSByteOrder.h and OSSwapLittleToHostInt16 in lieu of Linux's
endian.h and le16toh
Reported upstream to www-201506
AT
spiro
DOT 
trikaliotis DOT 
net
=> opencbm: fix endian.h porting issue

libmwaw/ctor.patch
fix call of explicit ctor
https://sourceforge.net/p/libmwaw/libmwaw/ci/4bc8ec0481f89b989b0c34236c9d5d9b8038d4a9/
=> libmwaw: add patch for 10.11 and below

gnumeric/textdomain.patch
Cherry-picks
https://github.com/GNOME/gnumeric/commit/7017a7ee2
https://github.com/GNOME/gnumeric/commit/64f1410b7
See https://bugzilla.gnome.org/show_bug.cgi?id=791951
=> gnumeric: add patch to avoid textdomain as a Gnumeric variable

gst-plugins-bad/0001-gl-cocoa-Implement-set_render_rectangle.patch
This patch was merged in gst-plugins-base upstream. GstGL was recently moved from -bad to
-base.
See https://cgit.freedesktop.org/gstreamer/gst-plugins-base/commit/?id=5d35e1fa15744b48c406fffa98695478fc8c9969
=> gst1-plugins-bad: add patch for Cocoa overlay set_render_rectangle API

transmission/CVE-2018-5702.patch
Grabbed patch directly from Ubuntu (transmission_2.92-2ubuntu3.1)[1].
[1] https://launchpad.net/ubuntu/+archive/primary/+files/transmission_2.92-2ubuntu3.1.debian.tar.xz
=> transmission: add patch for CVE-2018-5702

unbound/unbound-1.7.0-fix-v6-make-test.diff
only needed for unbound v1.7.0, merged upstream
=> unbound: fix IPv6 make test build failure

libtorrent-rasterbar/boost-1.67.diff
Reported upstream https://github.com/arvidn/libtorrent/issues/2947
=> libtorrent-rasterbar: add patch for Boost 1.67

moc/01-codec-2.5.2.patch, moc/01-codec.patch, moc/02-codecpar-2.5.2.patch, moc/02-codecpar.patch, moc/03-defines-2.5.2.patch, moc/03-defines.patch, moc/04-lockmgr-2.5.2.patch, moc/04-lockmgr.patch, moc/05-audio4-2.5.2.patch, moc/05-audio4.patch
For 2.6-alpha3, John Fitzgerald (upstream) provided via email
01-codec.patch
02-codecpar.patch
03-defines.patch
04-lockmgr.patch
05-audio4.patch
I have backported those to 2.5.2 as
01-codec-2.5.2.patch
02-codecpar-2.5.2.patch
03-defines-2.5.2.patch
04-lockmgr-2.5.2.patch
05-audio4-2.5.2.patch
=> moc: add patches for FFmpeg 4.0

go@1.9/go_19_load_commands.patch
This is upstream as https://github.com/golang/go/commit/1a92cdbfc10e0c66f2e015264a39159c055a5c15. Changes in the code structure meant this had to be changed slightly for 1.8 and 1.9.
=> Backport go 1.10/1.11 load commands patch

hfstospell/no-cxx17.diff
Adapt https://github.com/hfst/hfst-ospell/pull/41 to apply to configure
Goes together with https://github.com/Homebrew/homebrew-core/pull/29269.
=> hfstospell: add patch to avoid C++17

pyside/pyside-homebrew.patch
Issue: https://bugreports.qt.io/browse/PYSIDE-731
Upstream patch: http://code.qt.io/cgit/pyside/pyside-setup.git/commit/?h=5.11&id=5662706937bd6a1449538539e3a503c6cbc45399
The upstream patch needs an extra #include statement to be applied directly on 5.11.0. 
Further info about the formula: https://github.com/Homebrew/homebrew-core/pull/29699
=> pyside: patch to support build in superenv

upx/fix_decompression.patch
Adapts the upstream commit https://github.com/upx/upx/commit/aefb2fa3c3c9be723076d3fd49c5a4f69121f715. The upstream patch has the same logic, but doesn't apply cleanly because of surrounding refactoring.
=> upx: fix decompressing Mach executables

binutils/add_mach_o_command.patch
This fixes using `gnm` on macOS 10.14. This is the upstream commit with the changelog portions removed in order to allow it to apply to the stable release.
https://sourceware.org/bugzilla/show_bug.cgi?id=23728
https://github.com/Homebrew/homebrew-core/issues/32516
=> binutils: add patch for new mach-o load commands

libtiff/libtiff-CVE-2018-18557.patch
See https://github.com/Homebrew/homebrew-core/pull/33918#issuecomment-437013547.
I expect libtiff 4.0.10 [to be released soon](https://gitlab.com/libtiff/libtiff/commit/779e54ca32b09155c10d398227a70038de399d7d) and it will contain the same fix. This backport is a stop-gap until then. It contains multiple commits for clarity.
=> libtiff: backport patch for CVE-2018-18557

auditbeat/go1.11.diff
Adding a patch for go 1.11 support for `auditbeat`.
This is a partly backport of upstream commit https://github.com/elastic/beats/commit/8d8eaf34a6cb5f3b4565bf40ca0dc9681efea93c, which didn't apply cleanly (but I could just drop most of the failed chunks for being unrelated to `auditbeat` itself).
Refs: https://github.com/Homebrew/homebrew-core/pull/36659
=> auditbeat: add patch for Go 1.11

libtiff/libtiff-CVE-2019-6128.patch
[Fedora commit](https://src.fedoraproject.org/rpms/libtiff/c/3e70d60fe1ebf2ab0584e1df22a1db8e84ac15f4)
=> libtiff: CVE-2019-6128 patch for 4.0.10

auditbeat/go1.11.diff
This fails now to apply in `auditbeat`6.7.0 because it got already backported.
=> auditbeat 6.7.0 patch update

mmv/mmv_1.01b-15.diff
The mmv formula is trying to reference a gzipped patch that has been deleted from the debian servers:
* https://github.com/Homebrew/homebrew-core/blob/master/Formula/mmv.rb#L20-L21
* https://deb.debian.org/debian/pool/main/m/mmv/mmv_1.01b-15.diff.gz
I managed to find the patch at the following location with a matching sha256
* https://launchpadlibrarian.net/27360154/mmv_1.01b-15.diff.gz
* https://launchpad.net/ubuntu/+source/mmv/1.01b-15
I previously uploaded the gzipped patch in #267, but closed that in favor of an uncompressed patch here.
=> mmv: 1.01b-15 patch

ipopt/mumps-makefile-inc-generic-seq.patch
Inline patch from https://github.com/Homebrew/homebrew-core/blob/1d5abfab0488086c86402d8e7dcac9c433a0d682/Formula/ipopt.rb#L77. I will use this when I bump the version of IPOPT to 3.12.13.
=> ipopt: patch MUMPS Makefile.inc.generic.SEQ

go@1.10/dwarf_segments.patch
Backported from https://github.com/golang/go/commit/26954bde4443c4bfbfe7608f35584b6b810f3f2c.
=> go@1.10: add patch for malformed DWARF segments

libfreehand/0.1.2.patch
- Upstream bug fixed at https://git.libreoffice.org/libfreehand/+/af3197f795625f5188602073205a34369698b6df%5E!/
- Remove with >=0.1.3
=> libfreehand: add patch for 0.1.2

gmp/6.2.0-arm.patch
This commit consolidates the two patches proposed in https://github.com/Homebrew/homebrew-core/pull/57315.
=> gmp: add arm64 compatibility patch

acmetool/stable-gomod.diff
For building with go modules. Upstream has no branch to merge stable patches.
=> acmetool: add patch for 0.0.67 (remove gopath)

python/3.8.3.patch
This is a reboot of https://github.com/Homebrew/formula-patches/pull/287 due to https://github.com/Homebrew/homebrew-core/pull/57997.
___
This set of patches includes the following upstream pull requests:
- https://github.com/python/cpython/pull/20171, "Fix _tkinter use" (prerequisite for 21249)
- https://github.com/python/cpython/pull/21114, "Support `arm64` in Mac/Tools/pythonw"
- https://github.com/python/cpython/pull/21224, "allow python to build for macosx-11.0-arm64"
- https://github.com/python/cpython/pull/21249, "ctypes fixes for arm64 Mac OS"
Adding them here is warranted as `python@3.8` is widely used as a dependency, and the patch is required to enable testing dependent formulae.
Note that these have been successfully tested for `python@3.8` but not for `python`.
The patch …
=> python@3: add arm64 compatibility patches

perl/version_check.patch
Patch is based on this PR: https://github.com/Perl/perl5/pull/17946
Until this PR is merged the formula is blocked, so creating a patch as the PR is being modified/changed as the options moving forward are discussed
=> perl: Resolve macOS 11.0+ version check blocker

lbzip2/gnulib-vasnprintf-port-to-macOS-10-13.diff
Fix crash on macOS >= 10.13 due to an incompatibility in the embedded gnulib.
Original patch here: https://lists.gnu.org/archive/html/bug-gnulib/2017-07/msg00058.html
=> lbzip2: patch for 2.5

llvm/10.0.1-clang.diff, llvm/10.0.1-compiiler-rt.diff, llvm/10.0.1-lld.diff, llvm/10.0.1-lldb.diff, llvm/10.0.1-llvm.diff
These patches are required to solve https://discourse.brew.sh/t/llvm-config-10-0-1-advertise-libxml2-tbd-as-system-libs/8593/1
They were constructed by backporting the following commits to llvm's 10.x branch.
```
$ git cherry-pick 8c1a79dc12f3cc600e16153961cd8cc50ba2c33b
- fix conflicts lld/test/lit.site.cfg.py.in
$ git cherry-pick bcd27d9d73f74f291fbd8b0fd1182e69a327be88
- fix conflicts lld/test/lit.site.cfg.py.in
$ git cherry-pick 1d09ecf36175f7910ffedd6d497c07b5c74c22fb
- fix conflicts lld/test/lit.site.cfg.py.in
$ git cherry-pick 38c71b7c85cac4c8de39329ff3ed682e63f61525
- fix conflicts lld/test/lit.site.cfg.py.in
$ git cherry-pick 10b1b4a231a485f1711d576e6131f6755e008abe
- fix conflicts lld/test/lit.site.cfg.py.in
- delete mlir/examples/standalone/CMakeLists.txt
$ git cherry-pick …
```
=> llvm: patch for 10.0.1

upscaledb/2.2.1.diff
This patch is a combination of the following changes:
- https://github.com/cruppstahl/upscaledb/pull/97 (https://github.com/cruppstahl/upscaledb/commit/e62eea7b0dbe63e5007c1cf00c11dc661313732f)
- https://github.com/cruppstahl/upscaledb/pull/98 (https://github.com/cruppstahl/upscaledb/commit/98b4105fe852704da3d32ab72cb8a4317cbb1f6c)
- https://github.com/cruppstahl/upscaledb/pull/100 (https://github.com/cruppstahl/upscaledb/commit/9e7935ba72151f0dd766079ea77b3408508bfa18)
- https://github.com/cruppstahl/upscaledb/pull/110 (https://github.com/cruppstahl/upscaledb/commit/01156f9a894136b889a0ce6ab92dc2191c61ed15)
- https://github.com/cruppstahl/upscaledb/issues/124 (https://github.com/cruppstahl/upscaledb/commit/e2b655a26ade50daa26d33bcecd1b77e4a2d5ecc)
- …
=> upscaledb: patch for 2.2.1

openjdk@11/xcode12.diff
This patch backports the following changes (to get built `openjdk@11` on Xcode 12):
- https://github.com/openjdk/jdk/commit/f80a6066e45c3d53a61715abfe71abc3b2e162a1 (https://bugs.openjdk.java.net/browse/JDK-8253375)
- https://github.com/openjdk/jdk/commit/4622a18a72c30c4fc72c166bee7de42903e1d036 (https://bugs.openjdk.java.net/browse/JDK-8253791)
=> openjdk@11: fix build on Xcode 12

qt/qt3d-no-avx2-compile-fix.diff
Patch from: https://codereview.qt-project.org/c/qt/qt3d/+/303990
Patch is only available to download anonymously either in a zip archive or base64 encoded.
[homebrew-core#65128](https://github.com/Homebrew/homebrew-core/pull/65128#issuecomment-730153095)
=> qt: Added qt3d -no-avx2 compilation fix 

emacs/arm.patch
This PR adds a new patch that can be used to enable Apple Silicon Macs to get past configure. This is a backport of https://github.com/emacs-mirror/emacs/commit/b40a7056e53afd9d4ffdac03fd7b1b0fabb2a85d.patch from emacs master.
=> Patch for emacs 27.1 to enable building on Apple Silicon

kyoto-tycoon/ephemeral-ports.patch
This is just to support testing, since `free_port` seems to return mostly ephemeral ports.
=> kyoto-tycoon: ephemeral ports patch

cdparanoia/linux_fpic.patch
Original patch: https://gist.github.com/iMichka/c6d0ed5adb5375a8117d7c06999ae1be
Used in `linuxbrew-core/cdparanoia`: https://github.com/Homebrew/linuxbrew-core/blob/master/Formula/cdparanoia.rb#L29-L34
=> cdparanoia: add linux fpic patch

docbook-xsl/docbook-xsl-nons-1.79.2-stack_fix-1.patch
That website has download problems, see
https://github.com/Homebrew/homebrew-core/issues/67283#issuecomment-748593231.
Original URL:
http://www.linuxfromscratch.org/patches/blfs/9.1/docbook-xsl-nons-1.79.2-stack_fix-1.patch
Signed-off-by: Stefan Weil <sw@weilnetz.de>
=> docbook-xsl: add patch from www.linuxfromscratch.org

apr/r1882980+1882981-configure.patch
Incorporates the following from upstream:
* https://svn.apache.org/viewvc?view=revision&revision=1882980 (calls to exit() require stdlib.h or else we get -Werror,-Wimplicit-function-declaration)
* https://svn.apache.org/viewvc?view=revision&revision=1882981 (arpa/inet.h is required for inet_addr)
To be applied in https://github.com/Homebrew/homebrew-core/pull/68915
=> apr: configure rollup patch

llvm/lldb.patch
Patch taken from https://reviews.llvm.org/D95683, but the diff URL on
Phabricator is not stable.
See also https://github.com/Homebrew/homebrew-core/pull/70091.
=> llvm: add patch to fix lldb build

postgresql@10/icu4c68-2.patch
Patch adapted from https://svnweb.freebsd.org/ports/head/databases/postgresql10-server/files/patch-icu68?revision=553940&view=co.
=> postgresql@10: add patch for icu4c 68.2

openjdk@11/aarch64.diff
Fixed version of https://github.com/Homebrew/formula-patches/pull/345. 
Description from that PR as well.
This PR updates patch for openjdk@11 for Apple Silicon (https://github.com/Homebrew/formula-patches/commit/906561d59f9c9197acb44e5246f4adb71fef5bab) to make it compatible with [openjdk@11 11.0.10](https://github.com/Homebrew/homebrew-core/pull/69396):
- Remove patch for xcode 12 (it was applied by upstream)
- Update patch `src/hotspot/share/runtime/vm_version.hpp`
- Remove patch for `test/` directory — it has conflicts with upstream, I believe we don't really need it, so, just left upstream version of `test/`
<details>
<summary> The patch doesn't apply cleanly, but it applies (with some offsets) </summary>
<p>
```
==> Applying aarch64.diff
patch -g 0 -f -p1 -i …
```
=> openjdk@11: update aarch64 patch for 11.0.10

libffi/libffi-3.3-arm64.patch
Latest patches from Apple, with various fixes over the previous version.
Fixes the erroneous exclusion of `ffi_prep_closure`, which caused issues with Python's `cffi` etc.
=> libffi: update arm64 patch

lua/lua-dylib.patch
This is a modification of the emedded patch currently in the formula.
I've fixed it so that it shouldn't require updating as long as upstream
doesn't change their Makefiles significantly.
This also borrows from MacPorts' equivalent patches.
=> lua: move embedded patch

node@12/node@12-icu69.patch
This is a backport of https://github.com/v8/v8/commit/035c305ce7761f51328b45f1bd83e26aef267c9d.
Needed for https://github.com/Homebrew/homebrew-core/pull/74794.
=> node@12: add patch for ICU 69

llvm/llvm.patch
This patch was made for https://github.com/Homebrew/homebrew-core/pull/79465.  It will be merged into a future LLVM point release, after which it will not be needed.
=> llvm: add patch to build with gcc-5

llvm@9/llvm@9.patch
This patch was backported from https://github.com/llvm/llvm-project/commit/a3a24316087d0e1b4db0b8fee19cdee8b7968032 to LLVM 9 by MacPorts: https://github.com/macports/macports-ports/blob/master/lang/llvm-9.0/files/patch-clang-fix-include-next-sysroot-cpp-headers.diff.
=> llvm@9: patch clang driver for Big Sur

cgit/memrchr-impl.patch
This patch is taken from:
https://lists.zx2c4.com/pipermail/cgit/2020-August/004510.html
https://github.com/Homebrew/homebrew-core/pull/57096#issuecomment-651414881
=> cgit: add patch for missing memrchr() implementation

postgresql/openldap-2.5.patch
Reported upstream: https://www.postgresql.org/message-id/17083-a19190d9591946a7%40postgresql.org
Used by https://github.com/Homebrew/homebrew-core/pull/80643.
=> postgresql: enable building with OpenLDAP 2.5

nutcracker/use-system-libyaml.patch
This should help resolve a CI failure seen in
Homebrew/homebrew-core#78294.
While we're here, I should mention that it looks like `nutcracker`
vendors a bunch of other things, which might be why all the other
distros are still on an older version at the moment.
That isn't causing us problems at the moment, however, so let's focus on
fixing the things that are.
=> nutcracker: add patch to use Homebrew `libyaml`

libgsm/libgsm_shared_linux.patch, libgsm/libgsm_shared_mac.patch
These patches were originally hosted in other git repos.  They hardcode the library version, which now out of date.  In these versions, the placeholder SOVERSION is used instead, which will be replaced the current version in the formula with `inreplace`.
=> libgsm: add patches for building shared library

jhead/3.06.0.1.patch
This updates the existing `jhead` patch for 3.06.0.1 (`makefile` has changes that break the existing patch).
=> jhead: update patch for 3.06.0.1

pygit2/libgit2-1.2.0.patch
This allows the `pygit2` resource used in various formulae to build with
libgit2 1.2.0. This amends libgit2/pygit2@dcde9eff5950492ab0d2565a07fd18d765332a96
so that it applies to the PyPI tarball.
Supports Homebrew/hombrew-core#84518.
=> Add pygit2 patch

bdw-gc/crystal-mt.patch
This is a backport of ivmai/bdwgc@5668de71107022a316ee967162bc16c10754b9ce
so that it applies to the v8.0.6 tag.
The commit is applied with no changes, except for the changes to
`win32_threads.c`. The changes to this file are not relevant for our
purposes, and the original commit no longer applies.
This patch can be removed in v8.2.0.
=> bdw-gc: add multithreading patch

gcc/gcc-11.2-rtl-bug.diff
Upstream patch: https://gcc.gnu.org/pipermail/gcc-patches/2021-November/583031.html
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=103026
=> GCC: upstream RTL warning patch

irrlicht/use-system-libs.patch, irrlicht/xcode.patch
use-system-libs.patch has mixed CRLF and LF endings, and xcode.patch only has LF endings, hence the separate patch files.
=> irrlicht: add patches to use system libs

autogen/allow-guile-3.0.diff, autogen/flat-namespace.diff
Fix -flat_namespace being used on Big Sur and later.
Fix guile detection, see https://sourceforge.net/p/autogen/bugs/196/
The guile patch is almost the same as the 2.2 patch that was already in this repo.
Upstream said that they will disable that version check completely.
=> autogen: add guile 3.0 and flat namespace patches

ccextractor/unbundle-libs.patch
Upstream build script changed in https://github.com/CCExtractor/ccextractor/pull/1390. This PR updates existing patch to accommodate upstream changes.
=> ccextractor: update patch for 0.94

qt/qt_internal_check_if_path_has_symlinks.patch
Remove a symlink check which causes build to bail out and fail
=> qt: Create qt_internal_check_if_path_has_symlinks.patch

pdf2djvu/main-use-pdf-link-Destination-copy-constructor.patch
See https://github.com/Homebrew/homebrew-core/pull/98905
Signed-off-by: Yurii Kolesnykov <root@yurikoles.com>
=> pdf2djvu: port upstream patch for poppler 22.04.0 compatibility

percona-server/8.0.28-19.diff
This patch applies changes from https://github.com/mysql/mysql-server/commit/4498aef6d4a1fd266cdbddcce60965e3cb12fe1a to `percona-server` (fixed  unneeded copying of OpenSSL libs and finding libs from Homebrew)
Ref https://github.com/Homebrew/homebrew-core/pull/101876
=> percona-server: add 8.0.28-19 patch for cmake

liblinear/patch-Makefile.diff
The `LIBEXT` is handled differently on macOS and Linux, which makes the
current formula fail to install on Linux.
Needed for Homebrew/homebrew-core#103456.
=> liblinear: improve platform consistency

gnupg/2.4.0-setup-scm.patch
Adding this patch from upstream, https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git;a=commit;h=e89d57a2cb10bd04d266165015f159be2ab48984, to fix the build failure in https://github.com/Homebrew/homebrew-core/pull/118607.
=> gnupg: add setup-scm error patch

liblinear/patch-Makefile.diff
Needed for https://github.com/Homebrew/homebrew-core/pull/123516. The Makefile has changed quite a bit; but the contents of the patch are adapted from the previous one.
=> liblinear: update patch for 2.46

vlang/vc.patch
This adds an `#include` that's needed for macOS Big Sur and below.
=> vlang: vc resource patch

cdparanoia/osx_interface.patch
Sync patch from MacPorts
See macports/macports-ports@c8e15973bc3c
=> cdparanoia: Fix buffer overrun

qt5/chromium-binutils.patch
Modified version of patch for qt@5
Only the paths of the files to patch have been changed
=> qt@5: add patch for binutils >= 2.41

aalib/1.4rc5.patch
Building `aalib` on macOS Sonoma produces a number of implicit function declaration errors (see https://github.com/Homebrew/homebrew-core/issues/142161#issuecomment-1730715657). This modifies the existing patch to add more `#include` statements to resolve these errors.
I've created a draft homebrew/core PR that uses this (https://github.com/Homebrew/homebrew-core/pull/144725) and I will modify that PR to use this updated patch once available.
=> aalib: fix implicit function declarations

jam/2.6.1-undeclared_functions.diff
This fixes a couple of `undeclared function` errors that have surfaced on macOS Sonoma:
```
make1.c:392:8: error: call to undeclared function 'unlink'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
if( !unlink( targets->string ) )
^
make1.c:392:8: note: did you mean 'unlinkat'?
/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/include/sys/unistd.h:214:9: note: 'unlinkat' declared here
int     unlinkat(int, const char *, int) __OSX_AVAILABLE_STARTING(__MAC_10_10, __IPHONE_8_0);
^
1 error generated.
parse.c:102:20: error: call to undeclared function 'yylineno'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
p->yylineno = yylineno();
^
parse.c:102:20: note: did you mean 'yylineo'? …
```
=> jam: fix undeclared functions

apophenia/posix-basename.diff
Needed for https://github.com/Homebrew/homebrew-core/pull/146769. This patch is already upstreamed, but we can't use the patches of the upstream commit because they do not apply cleanly (there were other changes made in the repository between the last tagged release and these patches being committed).
=> apophenia: patch for basename(3) on non-GNU systems

unac/gcc-4-fix-bug-556379.patch, unac/update-autotools.diff
We're using Debian's 1.8.0-8 patches in the `unac` formula but the links to these patches are liable to break over time (https://github.com/Homebrew/homebrew-core/pull/146119#issuecomment-1736530511). Using our own copies of the patches will help to keep the formula working irrespective of Debian releases.
=> unac: add 1.8.0-8 patches

ettercap/libmaxminddb-backport.diff
The patch is the upstream commit with some diffs removed to apply:
* .github/workflows/build.yml - not in release and only CI file
* .github/workflows/codeql.yml - not in release and only CI file
* CHANGELOG - diff doesn't apply and only documentation
* README - diff doesn't apply and only documentation
* share/GeoLite2-Country.mmdb - GNU patch fails on binary files
https://github.com/Ettercap/ettercap/commit/741c4d3bcd5c3e37d7d6b0fe0e748a955b2f43f5
---
For https://github.com/Homebrew/homebrew-core/pull/157027 so we can deprecate `geoip` https://github.com/Homebrew/homebrew-core/pull/157028
=> ettercap: add patch for `libmaxminddb` support

daemontools/posix-headers.patch
This patchset is similar to that used by other packagers, e.g. https://git.alpinelinux.org/aports/plain/testing/daemontools/0.76-warnings.patch or https://raw.githubusercontent.com/macports/macports-ports/master/sysutils/daemontools/files/implicit.patch.
=> daemontools: patch for missing headers for POSIX functions

pyqt/qt-6.7.0.patch
Dropped some metadata modifications, public inheritance changes, and version number modification.
---
Needed for Homebrew/homebrew-core#169109 which should unblock LLVM PR.
---
Generated using PyQt6 stable source and https://www.riverbankcomputing.com/pypi/packages/PyQt6/PyQt6-6.7.0.dev2404171245.tar.gz (linked from https://www.riverbankcomputing.com/software/pyqt/download)
It might be possible to pare down patch to only incompatible API and drop new API, but didn't seem worth time to do this.
Tested a local run with patch applied from branch on ARM macOS, e.g.
```diff
diff --git a/Formula/p/pyqt.rb b/Formula/p/pyqt.rb
index c98f9cfb4d0..974248ade23 100644
--- a/Formula/p/pyqt.rb
+++ b/Formula/p/pyqt.rb
@@ -53,6 +53,12 @@ class Pyqt < Formula
sha256 …
```
=> pyqt: backport qt 6.7.0 support from PyQt6-6.7.0.dev2404171245

openssh/patch-sshd.c-apple-sandbox-named-external.diff
Original patch: https://raw.githubusercontent.com/Homebrew/patches/d8b2d8c2612fd251ac6de17bf0cc5174c3aab94c/openssh/patch-sshd.c-apple-sandbox-named-external.diff
The code we're patching was moved from sshd.c to sshd-session.c: https://cvsweb.openbsd.org/cgi-bin/cvsweb/src/usr.bin/ssh/sshd-session.c
=> openssh: update patches for 7.8p1

openssh/patch-sandbox-darwin.c-apple-sandbox-named-external.diff
This was removed in 0fe849ef2b0e5c4c971362a15d573a57325f8c52, which batch-removed unused patches. That might have been a mistake, since openssh still had two used patches at the time. The other patch was later replaced, but this one is still referenced by the current version of the openssh formula.
=> openssh: restore still-used patch

cracklib/2.10.1-endian.patch
Needed for https://github.com/Homebrew/homebrew-core/pull/178733.
Adapted from https://github.com/cracklib/cracklib/commit/30fc5628036146bd38101a48c05f2387da0b02de. Change already accepted upstream.
Hosting the change here instead of using upstream Git patch because upstream has since adjusted the directory structure of the source code, causing the patch not to apply cleanly on the tagged 2.10.1 release.
=> cracklib: add patch for 2.10.1 to build on Darwin

python/3.13-sysconfig.diff
Based on https://github.com/Homebrew/formula-patches/commit/6d2fba8de3159182025237d373a6f4f78b8bd203 with minor changes for updated source code in python 3.13.
Needed for https://github.com/Homebrew/homebrew-core/pull/182840
=> python@3.13: modify sysconfig

glib/hardcoded-paths.diff
The new girepository library (part of GLib 1.80+) is replacing gobject-introspection.
GObject-introspection has a patch that makes it work nicely with Homebrews `/opt/homebrew/lib/girepository-1.0` folder.
See https://github.com/Homebrew/homebrew-core/blob/master/Formula/g/gobject-introspection.rb#L52-L58 for the gobject-introspection patch.
CC @tschoonj
=> glib: add $HOMEBREW/lib/girepository-1.0 to girepository search path

usbutils/portable.patch
Do not build usbreset when `with_sysfs=false`
Do not install lsusb.py and usb-devices and their manpages when `with_sysfs=false`
=> usbutils: revisited portable.patch

glibc/2.17-aarch64-dl-machine.diff
This patch is a backport of [^1]. Along with [^2] (backport of [^3]), it allows glibc@2.17 to be built with the latest GNU ld.
Without this patch, build fails with:
<details>
<summary> Build error </summary>
```
gcc-11   -nostdlib -nostartfiles -shared -o /tmp/glibcA2.17-20241116-69269-z0jgov/glibc-2.17/build/elf/ld.so			\
-Wl,-z,combreloc -Wl,-z,relro -Wl,--hash-style=both -Wl,-z,defs 	\
/tmp/glibcA2.17-20241116-69269-z0jgov/glibc-2.17/build/elf/librtld.os -Wl,--version-script=/tmp/glibcA2.17-20241116-69269-z0jgov/glibc-2.17/build/ld.map		\
-Wl,-soname=ld-linux-aarch64.so.1			\
-Wl,-defsym=_begin=0
/usr/bin/ld: /tmp/glibcA2.17-20241116-69269-z0jgov/glibc-2.17/build/elf/librtld.os: relocation R_AARCH64_ABS32 against `a local symbol' can not be used when making a shared object
/usr/bin/ld: …
```
=> Add backported patch for glibc@2.17

sqlite/3.49.0-macos-linker.patch
https://github.com/Homebrew/homebrew-core/pull/206808
upstream discussion, https://sqlite.org/forum/forumpost/a179331cbb
```
├── lib
│   ├── libsqlite3.a
│   ├── libsqlite3.dylib -> libsqlite3.dylib.3.49.0
│   ├── libsqlite3.dylib.0 -> libsqlite3.dylib.3.49.0
│   ├── libsqlite3.dylib.3.49.0
│   └── pkgconfig
│       └── sqlite3.pc
```
```
├── lib
│   ├── libsqlite3.0.dylib -> libsqlite3.3.49.1.dylib
│   ├── libsqlite3.3.49.1.dylib
│   ├── libsqlite3.a
│   ├── libsqlite3.dylib -> libsqlite3.3.49.1.dylib
│   └── pkgconfig
│       └── sqlite3.pc
```
=> sqlite: add macos linker patch for 3.49.0 release

gdal/gdal-3.10.1-poppler-25.02.0.patch
- relates to https://github.com/OSGeo/gdal/pull/11805
- - https://github.com/Homebrew/homebrew-core/pull/206812
=> gdal: add build patch for poppler 25.02.0

liboggz/1.1.2-inttypes.patch
https://github.com/Homebrew/homebrew-core/pull/207099
=> liboggz: Include `<inttypes.h>` to fix missing printf format macros

gstreamer/gst-plugins-bad-svtav1.patch
Partial backport of https://gitlab.freedesktop.org/gstreamer/gstreamer/-/commit/6bdfaa4606c417be8a64f4494fe95ea30421c24b, to be applied atop 1.24.12.
=> gstreamer: backport patch to support svt-av1 >= 3.0.0

musepack/r479.patch, musepack/r482.patch, musepack/r491.patch
Work in progress. Trying to find which patches are needed to build among the upstream SVN revisions that haven't been released and some patches other distros are carrying.
482 and 491 allow installing shared library
```
r482 | r2d | 2013-10-21 16:34:18 -0400 (Mon, 21 Oct 2013) | 1 line
libmpcdec : added install and soversion
```
```
r491 | r2d | 2016-02-14 17:07:10 -0500 (Sun, 14 Feb 2016) | 9 lines
adapted patch 0001-shared.patch from buildroot:
https://git.busybox.net/buildroot/tree/package/musepack/0001-shared.patch
original changelog :
Fixup installation of shared mpcdec library.
Based on gentoo patch.
```
---
479 is part of `-fno-common` fixes
```
r479 | r2d | 2012-03-30 16:03:53 -0400 (Fri, 30 Mar 2012) | 1 line
add extern keyword to global variable declaration (don't know it worked …
```
=> musepack: upstream patches

pypy/tcl-tk.diff
Moving embedded patch from pypy formulae to here to avoid `HOMEBREW_PREFIX` inreplace.
* https://github.com/Homebrew/homebrew-core/blob/main/Formula/p/pypy.rb#L220-L239
* https://github.com/Homebrew/homebrew-core/blob/main/Formula/p/pypy3.10.rb#L231-L250
=> pypy: add patch for brew `tcl-tk` on Linux
